'use strict';
const crypto=require('crypto');
const SERVICE_ID='frost.callable.fabric';
const VERSION='1.1.0';
const CANONICAL_REPO='12ephods-source/centinal26';
const CANONICAL_GIT_SHA='6e5731bfbb073573c044bcc2e106d3906f6dddf5';
const SOURCE_IDENTITY=`github:${CANONICAL_REPO}@${CANONICAL_GIT_SHA}`;
const SOURCE_IDENTITY_SHA256='623c8ab6ae44939098fbdbd5f1b362d4239077498a277616f6dee76b38ada733';
const ADAPTER_SPEC_SHA256='96fedc9ec3affe883fd3fa8f67e1813db9ca153ce9cd3b3aea7fd3379268676a';
const MCP_PROTOCOL_VERSION='2025-06-18';
function canonical(v){if(v===null||typeof v!=='object')return JSON.stringify(v);if(Array.isArray(v))return`[${v.map(canonical).join(',')}]`;return`{${Object.keys(v).sort().map(k=>`${JSON.stringify(k)}:${canonical(v[k])}`).join(',')}}`;}
function sha256(v){return crypto.createHash('sha256').update(v).digest('hex');}
function validate(d,s,p='$'){if(!s||Object.keys(s).length===0)return;const t=s.type;if(t==='object'){if(d===null||Array.isArray(d)||typeof d!=='object')throw new Error(`${p}: expected object`);for(const k of s.required||[])if(!(k in d))throw new Error(`${p}.${k}: required`);const ps=s.properties||{};for(const[k,v]of Object.entries(d)){if(ps[k])validate(v,ps[k],`${p}.${k}`);else if(s.additionalProperties===false)throw new Error(`${p}.${k}: unexpected field`);}}else if(t==='string'&&typeof d!=='string')throw new Error(`${p}: expected string`);}
const OPERATIONS={
'system.health':{description:'Return canonical deployment health and source identity.',risk:'READ_ONLY',approval_required:false,allowed_roles:['operator','admin'],input_schema:{type:'object',properties:{},additionalProperties:false}},
'system.capabilities':{description:'Return the semantic capability contract.',risk:'READ_ONLY',approval_required:false,allowed_roles:['operator','admin'],input_schema:{type:'object',properties:{},additionalProperties:false}},
'frost.diagnostics.echo':{description:'Echo UTF-8 text and return its code-point length.',risk:'READ_ONLY',approval_required:false,allowed_roles:['operator','admin'],input_schema:{type:'object',required:['text'],properties:{text:{type:'string'}},additionalProperties:false}},
'frost.diagnostics.sha256':{description:'Hash UTF-8 text with SHA-256.',risk:'READ_ONLY',approval_required:false,allowed_roles:['operator','admin'],input_schema:{type:'object',required:['text'],properties:{text:{type:'string'}},additionalProperties:false}},
'frost.diagnostics.canonicalize':{description:'Canonicalize a JSON value and hash it.',risk:'READ_ONLY',approval_required:false,allowed_roles:['operator','admin'],input_schema:{type:'object',required:['value'],properties:{value:{}},additionalProperties:false}},
'frost.diagnostics.dangerous_demo_policy_test':{description:'Guardian negative-control; no destructive implementation.',risk:'DESTRUCTIVE',approval_required:true,allowed_roles:['admin'],input_schema:{type:'object',required:['target'],properties:{target:{type:'string'}},additionalProperties:false}}
};
const manifest={service_id:SERVICE_ID,version:VERSION,canonical_repo:CANONICAL_REPO,canonical_git_sha:CANONICAL_GIT_SHA,source_identity:SOURCE_IDENTITY,source_identity_sha256:SOURCE_IDENTITY_SHA256,deployment_adapter_sha256:ADAPTER_SPEC_SHA256,protocols:['frost-call/1.0',`mcp/${MCP_PROTOCOL_VERSION}`],policy:{semantic_tools_only:true,unrestricted_remote_shell:false,guardian:true,schema_validation:true,provenance_receipt:true},operations:OPERATIONS};
function authorize(op,c={}){const role=c.role||'operator';if(!(op.allowed_roles||['operator','admin']).includes(role))return{allowed:false,reason:`role ${JSON.stringify(role)} not allowed`};if((op.approval_required||op.risk==='DESTRUCTIVE')&&!c.approved)return{allowed:false,reason:`${op.risk} requires explicit approval`};if(op.risk==='DESTRUCTIVE'&&role!=='admin')return{allowed:false,reason:'DESTRUCTIVE requires admin role'};return{allowed:true,reason:'authorized'};}
function redact(a){const s=new Set(['password','passwd','token','secret','api_key','authorization']);return Object.fromEntries(Object.entries(a||{}).map(([k,v])=>[k,s.has(k.toLowerCase())?'<redacted>':v]));}
function healthResult(){return{ok:true,service:SERVICE_ID,version:VERSION,canonical_repo:CANONICAL_REPO,canonical_git_sha:CANONICAL_GIT_SHA,source_identity_sha256:SOURCE_IDENTITY_SHA256,deployment_adapter_sha256:ADAPTER_SPEC_SHA256,semantic_tools_only:true,unrestricted_remote_shell:false};}
function execute(o,a){switch(o){case'system.health':return healthResult();case'system.capabilities':return{manifest};case'frost.diagnostics.echo':return{text:a.text,length:[...a.text].length};case'frost.diagnostics.sha256':return{sha256:sha256(Buffer.from(a.text,'utf8'))};case'frost.diagnostics.canonicalize':{const c=canonical(a.value);return{canonical_json:c,sha256:sha256(Buffer.from(c,'utf8'))};}case'frost.diagnostics.dangerous_demo_policy_test':return{target:a.target,executed:false,reason:'policy-test operation has no destructive implementation'};default:throw new Error('operation not implemented');}}
function receipt(b){return{...b,record_hash:sha256(Buffer.from(canonical(b),'utf8'))};}
function invoke(s,o,a={},c={}){const started=Date.now(),id=c.request_id||crypto.randomUUID(),common={request_id:id,service_id:s,operation:o,caller:c.caller||'https',role:c.role||'operator',canonical_git_sha:CANONICAL_GIT_SHA,source_identity_sha256:SOURCE_IDENTITY_SHA256,deployment_adapter_sha256:ADAPTER_SPEC_SHA256,request_hash:sha256(Buffer.from(canonical({service_id:s,operation:o,arguments:redact(a)}),'utf8'))};if(s!==SERVICE_ID){const r=receipt({...common,event:'INVOCATION_NOT_FOUND',timestamp:new Date().toISOString()});return{ok:false,error:{type:'NOT_FOUND',message:'service not registered'},receipt:r};}const op=OPERATIONS[o];if(!op){const r=receipt({...common,event:'INVOCATION_NOT_FOUND',timestamp:new Date().toISOString()});return{ok:false,error:{type:'NOT_FOUND',message:'operation not registered'},receipt:r};}const g=authorize(op,c);if(!g.allowed){const r=receipt({...common,guardian:g,event:'INVOCATION_DENIED',timestamp:new Date().toISOString()});return{ok:false,request_id:id,service_id:s,operation:o,error:{type:'DENIED',message:g.reason},receipt:r};}try{validate(a,op.input_schema);const result=execute(o,a),result_hash=sha256(Buffer.from(canonical(result),'utf8')),elapsed_ms=Date.now()-started,r=receipt({...common,guardian:g,event:'INVOCATION_OK',result_hash,elapsed_ms,timestamp:new Date().toISOString()});return{ok:true,request_id:id,service_id:s,operation:o,result,diagnostics:{elapsed_ms,version:VERSION,canonical_git_sha:CANONICAL_GIT_SHA,source_identity_sha256:SOURCE_IDENTITY_SHA256,deployment_adapter_sha256:ADAPTER_SPEC_SHA256,result_hash},receipt:r};}catch(e){const r=receipt({...common,guardian:g,event:'INVOCATION_ERROR',error_type:e.name||'Error',error:String(e.message||e),timestamp:new Date().toISOString()});return{ok:false,error:{type:e.name||'Error',message:String(e.message||e)},receipt:r};}}
function mcpToolName(n){return n.replace(/[^A-Za-z0-9_-]/g,'_');}
function mcpTools(){return Object.entries(OPERATIONS).map(([n,o])=>({name:mcpToolName(n),description:`${n}: ${o.description}`,inputSchema:o.input_schema||{type:'object'}}));}
function mcpCall(n,a={},m={}){const o=Object.keys(OPERATIONS).find(x=>mcpToolName(x)===n);return o?invoke(SERVICE_ID,o,a,{caller:'mcp',role:m.role||'operator',approved:Boolean(m.approved),request_id:m.request_id}):null;}
function verifyReceipt(v){if(!v||typeof v!=='object'||typeof v.record_hash!=='string')return false;const b={...v},e=b.record_hash;delete b.record_hash;return sha256(Buffer.from(canonical(b),'utf8'))===e;}
module.exports={SERVICE_ID,VERSION,CANONICAL_GIT_SHA,SOURCE_IDENTITY,SOURCE_IDENTITY_SHA256,ADAPTER_SPEC_SHA256,MCP_PROTOCOL_VERSION,manifest,canonical,sha256,invoke,mcpTools,mcpCall,healthResult,verifyReceipt};
