import json
import sys
import unittest
from pathlib import Path
from unittest import mock

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
import transcribe as t


class TestTranscriber(unittest.TestCase):
    def test_extract_video_id_youtu_be(self):
        self.assertEqual(t.extract_video_id("https://youtu.be/tr9AqDYxFI4?si=test"), "tr9AqDYxFI4")

    def test_extract_video_id_watch(self):
        self.assertEqual(t.extract_video_id("https://www.youtube.com/watch?v=tr9AqDYxFI4&x=1"), "tr9AqDYxFI4")

    def test_select_caption_human_source_first(self):
        meta = {"language": "es", "subtitles": {"en": [{}], "es": [{"url": "x"}]}, "automatic_captions": {"es": [{"url": "y"}]}}
        self.assertEqual(t.select_caption(meta), ("human", "es"))

    def test_select_caption_auto(self):
        self.assertEqual(t.select_caption({"language": "en", "automatic_captions": {"en": [{"url": "x"}]}}), ("auto", "en"))

    def test_vtt_duplicate_merge(self):
        raw = """WEBVTT\n\n00:00:00.000 --> 00:00:02.000\nHello &amp; welcome\n\n00:00:01.900 --> 00:00:03.000\nHello &amp; welcome\n\n00:00:03.100 --> 00:00:05.000\nSecond line\n"""
        segs = t.parse_vtt_text(raw)
        self.assertEqual(len(segs), 2)
        self.assertEqual(segs[0]["text"], "Hello & welcome")
        self.assertEqual(segs[0]["end"], 3.0)

    def test_validation_low_confidence_review(self):
        r = t.validate([{"start": 0.0, "end": 9.0, "text": "hello"}], 10.0, [0.4, 0.5], "whisper.cpp")
        self.assertEqual(r["status"], "REVIEW")

    def test_validation_clean_caption_pass(self):
        r = t.validate([{"start": 0.0, "end": 9.5, "text": "hello"}], 10.0, [], "caption_human")
        self.assertEqual(r["status"], "PASS")

    def test_piped_caption(self):
        listing = json.dumps({"subtitles": [{"code": "en", "url": "/en.vtt", "mimeType": "text/vtt", "autoGenerated": True}]})
        vtt = "WEBVTT\n\n00:00:00.000 --> 00:00:02.000\nHello from Piped\n"
        def fake_get(url, timeout=15.0):
            return listing if "/streams/" in url else vtt
        with mock.patch.object(t, "PIPED_INSTANCES", ("https://example.invalid",)), mock.patch.object(t, "http_get", side_effect=fake_get):
            segs, kind, lang = t.piped_caption("tr9AqDYxFI4", ["en"])
        self.assertEqual((kind, lang, segs[0]["text"]), ("piped", "en", "Hello from Piped"))

    def test_whisper_segments(self):
        raw = {"result": {"language": "en"}, "transcription": [{"offsets": {"from": 1000, "to": 2500}, "text": " Hi", "tokens": [{"p": 0.9}]}]}
        segs, probs, lang = t.whisper_segments(raw, "", 3.0)
        self.assertEqual(segs[0], {"start": 1.0, "end": 2.5, "text": "Hi"})
        self.assertEqual(probs, [0.9])
        self.assertEqual(lang, "en")

    def test_language_helpers(self):
        self.assertTrue(t.is_english("en-US"))
        self.assertEqual(t.base_lang("es-MX"), "es")


if __name__ == "__main__":
    unittest.main()
